# AWS SAM template for testing Lambda locally, we use Terraform as deployment framework
Resources:
  Syncer:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs16.x
      Handler: dist/index.handler
      MemorySize: 256
      Timeout: 300
      Environment:
        Variables:
          GITHUB_RUNNER_ALLOW_PRERELEASE_BINARIES:
          GITHUB_RUNNER_ARCHITECTURE:
          GITHUB_RUNNER_OS:
          LOG_LEVEL:
          LOG_TYPE:
          S3_BUCKET_NAME:
          S3_OBJECT_KEY:
